# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=20, verbose_name='姓名')),
                ('p_no', models.CharField(max_length=20, verbose_name='工号')),
                ('p_dep', models.CharField(max_length=50, verbose_name='部门')),
                ('p_in_date', models.DateField(verbose_name='入职时间')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50, verbose_name='项目名')),
                ('p_launch_date', models.DateField(verbose_name='启动时间')),
            ],
        ),
        migrations.CreateModel(
            name='WorkRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_hours', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='时长')),
                ('p_work_date', models.DateField(verbose_name='工作日')),
                ('p_add_time', models.DateTimeField(verbose_name='录入时间')),
                ('p_comment', models.CharField(default='', max_length=400, verbose_name='备注')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manday.Person', verbose_name='人员')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manday.Project', verbose_name='项目名')),
            ],
        ),
        migrations.AlterIndexTogether(
            name='person',
            index_together=set([('p_name',)]),
        ),
    ]
