# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manday', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecord',
            name='p_work_date',
            field=models.DateField(verbose_name='工作日期'),
        ),
    ]
