# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manday', '0002_auto_20170901_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecord',
            name='p_hours',
            field=models.FloatField(verbose_name='时长'),
        ),
    ]
